// AUTO-GENERATED by scripts/snapshotHeroExamples.mjs — do not edit by hand.
// Real standard-mode SecURL grades, snapshotted 2026-06-06T10:34:35.931Z.
// Refresh with: npm run snapshot:hero
export type ChipSeverity = "critical" | "warning" | "info";

export interface HeroExampleChip {
  label: string;
  sev: ChipSeverity;
}

export interface HeroExample {
  domain: string;
  grade: string;
  score: number;
  label: string;
  critical: number;
  warning: number;
  info: number;
  chips: HeroExampleChip[];
}

export const HERO_EXAMPLES_GENERATED_AT = "2026-06-06T10:34:35.931Z";

export const HERO_EXAMPLES: HeroExample[] = [
  {
    domain: "mozilla.org",
    grade: "C",
    score: 76,
    label: "Mixed posture",
    critical: 0,
    warning: 3,
    info: 2,
    chips: [
    { label: "CORP missing", sev: "warning" },
    { label: "Weak CSP", sev: "warning" },
    { label: "HSTS weak", sev: "warning" },
    ],
  },
  {
    domain: "github.com",
    grade: "C",
    score: 72,
    label: "Mixed posture",
    critical: 0,
    warning: 2,
    info: 2,
    chips: [
    { label: "COOP missing", sev: "warning" },
    { label: "CORP missing", sev: "warning" },
    { label: "Cookie hygiene", sev: "info" },
    ],
  },
  {
    domain: "cloudflare.com",
    grade: "D",
    score: 66,
    label: "Needs attention",
    critical: 0,
    warning: 4,
    info: 2,
    chips: [
    { label: "Cookie hygiene", sev: "warning" },
    { label: "Weak CSP", sev: "warning" },
    { label: "Redirect chain detected", sev: "info" },
    ],
  },
  {
    domain: "google.com",
    grade: "D",
    score: 64,
    label: "Needs attention",
    critical: 0,
    warning: 8,
    info: 2,
    chips: [
    { label: "CSP missing", sev: "warning" },
    { label: "Cookie hygiene", sev: "warning" },
    { label: "COOP missing", sev: "warning" },
    ],
  },
];
